name: lu7creative
version: '3.0-SNAPSHOT'
main: com.lu7creative.lu7creative.lu7creative
author: 'Andrew Peacock'
description: This is a public version of the custom plugin used on the LU7 Creative Minecraft server. It has been adapted slightly for public use.
api-version: '1.20'

commands:
  lu7creativereload:
    description: Reload the LU7 Creative plugin configuration
    usage: /lu7creativereload
  lu7creativetest:
    description: Send a test notification
    usage: /lu7creativetest <message>

permissions:
  lu7creative.presencebypass:
    description: Bypasses Presence-Notifications for this user.
    default: false